#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 manage.py makemigrations

python3 manage.py migrate

python3 manage.py collectstatic --noinput


python3 manage.py shell <<EOF
from django.contrib.auth import get_user_model
User = get_user_model()

if not User.objects.filter(username='admin').exists():
    User.objects.create_superuser('admin', 'admin@gmail.com', 'SecurePassword')
EOF

exec gunicorn core.wsgi:application --bind 0.0.0.0:8080 --timeout 120

